### ISSUE TITLE
exit 1 when try to generate "Find Nearest Right Node in Binary Tree"(premium problem)

### ISSUE THREAD

**Issue by budougumi0617** [budougumi0617/leetgode#10]
```bash
$ go run ./cmd/leetgode/main.go generate 1745
exit status 1
```

https://leetcode.com/problemset/all/?search=Find%20Nearest%20Right%20Node%20in%20Binary%20Tree
https://leetcode.com/problems/find-nearest-right-node-in-binary-tree/

because premium problem?

**Comment by budougumi0617** [comment]
in result by leetcode-cli

> error: Not support premium question for now

**Comment by budougumi0617** [comment]
@hgsgtk
ちょっと理由はわからないのですが、課金しないと解けない問題のレスポンスのメタデータでjson syntax errorが起きているっぽいので問題が発生する前に落ちるようにしました 😇

**Comment by hgsgtk** [comment]
ふええ
